### ISSUE TITLE
[REQUEST] Showing server's messages

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/9x9-mobile#10]
**Is your feature request related to a problem? Please describe.**
The app doesn't display any server messages.

**Describe the solution you'd like**
There should at least an option in settings to turn on showing up ERR and DBG messages in pop-ups.

**Describe alternatives you've considered**
It can just display at the bottom on the screen like e. g. the status bar of something. Or the notifications also would be nice.

**Additional context**
Or there can be an option to switch between the status bar and pop-ups and notifications.

**Comment by miloszwasacz** [comment]
Added Developer Options - user can view errors and debug sent by server. ~~Will be implemented in upcomming release.~~ Implemented in [v0.2.2](https://github.com/Pikne-Programy/9x9-mobile/releases)
