### ISSUE TITLE
[BUG] Protocol error handling

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/9x9-mobile#12]
**Describe the bug**
I can connect to the `google.com` server with 80 port.

**To Reproduce**
1. Set the `google.com` server and `80` port.
2. Try to connect to any room.
3. There's no error. (it just waits for another player)

**Expected behavior**
An error should show up that the server didn't respond with a correct 9x9 Protocol message.

**Screenshots**
Just believe me.

**Device information (please complete the following information):**
 - Device: Lark G4s
 - OS Version: Android 6.0

**Additional context**
On the experimental WebSockets version, there should be also an error if the WebSocket connection failed.
And also another error should show up when the server is offline (so the server doesn't respond in any way).

**Comment by miloszwasacz** [comment]
> There's no error. (it just waits for another player)

So it doesn't show the board?

**Comment by Nircek** [comment]
There is the board in the background but I can't interact with it because there is a "waiting for another player" dialog.

**Comment by miloszwasacz** [comment]
Added Toast "Connection error" when trying to connect to wrong server. ~~Will be implemented in upcomming release.~~ Implemented in [v0.3.3](https://github.com/Pikne-Programy/9x9-mobile/releases)
