### ISSUE TITLE
[REQUEST] The sound signal

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/9x9-mobile#13]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to check the board status every second for about a minute.

**Describe the solution you'd like**
In my view, there should be a sound signal when it's my turn.

**Describe alternatives you've considered**
There can be also a notification with the possibility to add vibration, flashlight, etc.

**Comment by miloszwasacz** [comment]
Added sound and vibration on the start of your round (can be disabled in Settings). ~~Will be implemented in upcomming release.~~ Implemented in [v0.3.4](https://github.com/Pikne-Programy/9x9-mobile/releases)
