### ISSUE TITLE
[BUG] Dark theme problems on v2.1

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/9x9-mobile#4]
**Describe the bug**
There are problems with the dark theme. The text in several places is barely seen or invisible. And the main menu doesn't update after a theme change, the restart of the app is needed.

**To Reproduce**
1. Install v2.1
2. Assert the theme is light
3. Go to the settings
4. Change a theme from light to dark
5. Click the theme option again
6. Spot the black font on the gray background (**barely seen**)
7. Click back
8. Spot the **artifact light theme** on the room chooser
9. Join the server's room where is no player
10. Spot the joining message with the white font on the white background (**invisible**)

**Expected behavior**
The font should be visible and the main menu should update a theme after the change.

**Screenshots**
Barely seen:
![image](https://user-images.githubusercontent.com/26528678/77240036-af3c4e00-6be1-11ea-9251-7cda972c4bc9.png)
Invisible:
![image](https://user-images.githubusercontent.com/26528678/77240037-b4999880-6be1-11ea-8c34-a93280449ddd.png)

**Device information (please complete the following information):**
 - Device: LG G4s
 - OS Version: Android 6.0 Marshmallow (API 23)

**Comment by miloszwasacz** [comment]
Fixed issue by changing theme to "Theme.MaterialComponents.DayNight.DarkActionBar". ~~Will be implemented in upcomming release.~~ Implemented in [v0.2.2](https://github.com/Pikne-Programy/9x9-mobile/releases)
