### ISSUE TITLE
[REQUEST] The marked subboard where an enemy will make a move

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/9x9-mobile#6]
**Is your feature request related to a problem? Please describe.**
When I wait for my enemy to make a turn, I'd love to see where it will be because I can think with my enemy and compare my predicted move with the actual move.

**Describe the solution you'd like**
The subboard that the enemy has to make a move should be marked somehow. The actual marking of the subboard where I have to take a turn is a dark blue border and a blue filling. The marking of the enemy's subboard should be different. I'm concerned the red color ought to stand out.

**Describe alternatives you've considered**
There can be also only a border seen without any other color filling.

**Comment by miloszwasacz** [comment]
Added subboard marking on opponent's turn. ~~Will be implemented in upcomming release.~~ Implemented in [v0.2.2](https://github.com/Pikne-Programy/9x9-mobile/releases)
