### ISSUE TITLE
[BUG] The rendering problems with big 'O's

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/9x9-mobile#7]
**Describe the bug**
Sometimes the board doesn't consist of squares.

**To Reproduce**
1. Make 3 big 'O's in one row

**Expected behavior**
It should render normally. There should be squares.

**Screenshots**
![image](https://user-images.githubusercontent.com/26528678/77248390-5c8e8080-6c39-11ea-84aa-f8166b689b73.png)

**Device information (please complete the following information):**
 - Device: LG G4s
 - OS Version: Android 6.0

**Comment by miloszwasacz** [comment]
Does this occur only with 3 O's or also with X's?

**--Edit--**
It occurs with both big shapes.

**Comment by miloszwasacz** [comment]
Fixed issue by setting button visibility to "INVISIBLE" instead of "GONE". ~~Will be implemented in upcomming release.~~ Implemented in [v0.2.2](https://github.com/Pikne-Programy/9x9-mobile/releases)
