### ISSUE TITLE
[REQUEST] The last move

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/9x9-mobile#8]
**Is your feature request related to a problem? Please describe.**
I'm very frustrated when I have to make a move and I don't know what the latest move was.

**Describe the solution you'd like**
The last change on the board should be signed somehow. The purple border would be nice.

**Describe alternatives you've considered**
It can be black also but it must be thicker than the normal one.

**Additional context**
Don't know if you can do it yourself. Maybe some changes in the 9x9 Protocol should be requested.

**Comment by miloszwasacz** [comment]
Because of the fact that my app doesn't have any game logic I think that you should change the protocol.

**Comment by Nircek** [comment]
Make the issue in [Pikne-Programy/9x9-server](https://github.com/Pikne-Programy/9x9-server).

**Comment by miloszwasacz** [comment]
Added lastMove handling - icon color changes to purple. Will be implemented in upcomming release.
